### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gberche-orange** [Altoros/cf-chaos-loris-broker#1]
Thanks @allomov for this great contribution. I did not see a LICENSE file clarifying the usage terms of this contribution. Would you mind adding one ?

Thanks in advance,

Guillaume.

**Comment by allomov** [comment]
I am glad you appreciated the project. And sure, I've added the license file here (https://github.com/Altoros/cf-chaos-loris-broker/commit/a0c67b326ec5ed194cc416feb87c14e404e1e47a).

Several things for a notice (I'll put them to README later):
1. The project is in WIP phase, so be careful if you use it
1. We've build a pipeline to use the chaos loris with SB [here](https://github.com/Altoros/concourse-deploy-chaos-loris).
1. because of this issue https://github.com/strepsirrhini-army/chaos-loris/pull/10 you sould not consider to use strepsirrhini-army/chaos-loris in production environment (it kills all app's instances without paying attention to probability you specify). We use our [fork of chaos-loris](https://github.com/Altoros/chaos-loris/tree/develop) for deployment (see `develop` brunch there).
